# Makefile for bambi, utilities for the Sequence Alignment/Map format.
#
#    Copyright (C) 2016 Genome Research Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

ifeq ($(DEBUG), 1)
CFLAGS   = -g -Wall -O0 -DDEBUG
else
CFLAGS   = -Wall -O3 -DNDEBUG
endif

CC       = gcc
LDFLAGS  =
LIBS     =

OBJS=		decode.o i2b.o posfile.o filterfile.o bclfile.o hts_addendum.o

prefix      = /usr/local
exec_prefix = $(prefix)
bindir      = $(exec_prefix)/bin
datarootdir = $(prefix)/share
mandir      = $(datarootdir)/man
man1dir     = $(mandir)/man1

MKDIR_P = mkdir -p
INSTALL = install -p
INSTALL_PROGRAM = $(INSTALL)
INSTALL_DATA    = $(INSTALL) -m 644
INSTALL_DIR     = $(MKDIR_P) -m 755


PROGRAMS = bambi

BUILT_TEST_PROGRAMS = \
    test/bclfile/bclfile \
    test/posfile/posfile \
    test/filterfile/filterfile \
	test/decode/decode \
    test/i2b/i2b

all: $(PROGRAMS) $(BUILT_TEST_PROGRAMS)

# TODO Use configure or htslib.pc to add -rdynamic/-ldl conditionally
ALL_CPPFLAGS = -I. -I/usr/include/libxml2 $(HTSLIB_CPPFLAGS) $(CPPFLAGS)
ALL_LDFLAGS  = -rdynamic $(HTSLIB_LDFLAGS) $(LDFLAGS)
ALL_LIBS     = -lz -ldl -lxml2 $(LIBS)

# Usually config.mk and config.h are generated by running configure
# or config.status, but if those aren't used create defaults here.

config.mk:
	@sed -e '/^prefix/,/^LIBS/d;s/@Hsource@//;s/@Hinstall@/#/;s#@HTSDIR@#../htslib#g;s/@HTSLIB_CPPFLAGS@/-I$$(HTSDIR)/g;s/@CURSES_LIB@/-lcurses/g' config.mk.in > $@

include config.mk


PACKAGE_VERSION = 0.1

version.h:
	echo '#define BAMBI_VERSION "$(PACKAGE_VERSION)"' > $@

print-version:
	@echo $(PACKAGE_VERSION)


.SUFFIXES: .c .o

.c.o:
	$(CC) $(CFLAGS) $(ALL_CPPFLAGS) -c -o $@ $<


bambi: $(OBJS) $(HTSLIB) bambi.o
	$(CC) -pthread $(ALL_LDFLAGS) -o $@ bambi.o $(OBJS) $(HTSLIB_LIB) $(CURSES_LIB) -lm $(ALL_LIBS)

i2b.o: i2b.c $(htslib_sam_h) $(htslib_khash_h) $(htslib_kstring_h) $(sam_opts_h)
decode.o: decode.c $(htslib_sam_h) $(htslib_khash_h) $(htslib_kstring_h) $(sam_opts_h)
bambi.o: bambi.c $(htslib_hts_h) version.h
hts_addendum.o: hts_addendum.h

# test programs

check test: bambi $(BUILT_TEST_PROGRAMS)
	test/bclfile/bclfile
	test/filterfile/filterfile
	test/posfile/posfile
	test/decode/decode
	test/i2b/i2b

test/decode/decode: test/decode/decode.o $(HTSLIB)
	$(CC) -pthread $(ALL_LDFLAGS) -o $@ test/decode/decode.o hts_addendum.o $(HTSLIB_LIB) $(ALL_LIBS)

test/decode/decode.o: test/decode/decode.c decode.o hts_addendum.o

test/i2b/i2b: test/i2b/i2b.o $(HTSLIB)
	$(CC) -pthread $(ALL_LDFLAGS) -o $@ test/i2b/i2b.o posfile.o filterfile.o bclfile.o hts_addendum.o $(HTSLIB_LIB) $(ALL_LIBS)

test/i2b/i2b.o: test/i2b/i2b.c i2b.o hts_addendum.o

test/posfile/posfile: test/posfile/posfile.o posfile.o
	$(CC) $(ALL_LDFLAGS) -o $@ test/posfile/posfile.o posfile.o $(ALL_LIBS)

test/bclfile/bclfile: test/bclfile/bclfile.o bclfile.o
	$(CC) $(ALL_LDFLAGS) -o $@ test/bclfile/bclfile.o bclfile.o $(ALL_LIBS)

test/filterfile/filterfile: test/filterfile/filterfile.o filterfile.o
	$(CC) $(ALL_LDFLAGS) -o $@ test/filterfile/filterfile.o filterfile.o $(ALL_LIBS)

install: $(PROGRAMS) $(BUILT_MISC_PROGRAMS)
	$(INSTALL_DIR) $(DESTDIR)$(bindir) $(DESTDIR)$(man1dir)
	$(INSTALL_PROGRAM) $(PROGRAMS) $(MISC_PROGRAMS) $(DESTDIR)$(bindir)
	$(INSTALL_DATA) $(DESTDIR)$(man1dir)



clean:
	-rm -f *.o misc/*.o test/*.o test/*/*.o version.h
	-rm -f $(PROGRAMS) $(BUILT_TEST_PROGRAMS)

distclean: clean
	-rm -f config.cache config.log config.status

.PHONY: all check test clean distclean install
