/*  adapters.h -- index adapter subcommand.

    Copyright (C) 2019 Genome Research Ltd.

    Author: Jennifer Liddle <js10@sanger.ac.uk>
    
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
    
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/  
    



typedef struct {
    char *name;
    char *fwd;
    char *rev;
    int score;
    int begin;
    int end;
    int len;
    float frac;
    float pfrac;
    bool revmatch;
    int seqstart;
} adapter_t;

adapter_t adapterArray[] = {
    {"DpnII-Gex-Adapter1-1", "GATCGTCGGACTGTAGAACTCTGAAC", "GTTCAGAGTTCTACAGTCCGACGATC" },
    {"DpnII-Gex-Adapter1-2", "ACAGGTTCAGAGTTCTACAGTCCGAC", "GTCGGACTGTAGAACTCTGAACCTGT" },
//    {"DpnII-Gex-Adapter2-1", "CAAGCAGAAGACGGCATACGANN", "NNTCGTATGCCGTCTTCTGCTTG" },
    {"DpnII-Gex-Adapter2-2", "TCGTATGCCGTCTTCTGCTTG", "CAAGCAGAAGACGGCATACGA" },
    {"DpnII-Gex-PCR-Primer1", "CAAGCAGAAGACGGCATACGA", "TCGTATGCCGTCTTCTGCTTG" },
    {"DpnII-Gex-PCR-Primer2", "AATGATACGGCGACCACCGACAGGTTCAGAGTTCTACAGTCCGA", "TCGGACTGTAGAACTCTGAACCTGTCGGTGGTCGCCGTATCATT" },
    {"DpnII-Gex-SequencingPrimer", "CGACAGGTTCAGAGTTCTACAGTCCGACGATC", "GATCGTCGGACTGTAGAACTCTGAACCTGTCG" },
    {"Nextflex-PCR-1", "AATGATACGGCGACCACCGAGATCTACAC", "GTGTAGATCTCGGTGGTCGCCGTATCATT" },
    {"Nextflex-PCR-2", "CAAGCAGAAGACGGCATACGAGAT", "ATCTCGTATGCCGTCTTCTGCTTG" },
    {"Nextflex-barcode(degenerate)", "GATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG", "CAAGCAGAAGACGGCATACGAGATNNNNNNGTGACTGGAGTTCAGACGTGTGCTCTTCCGATC" },
    {"PE-PCR-Primers1-1", "AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT", "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT" },
    {"PE-PCR-Primers1-2", "CAAGCAGAAGACGGCATACGAGATCGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT", "AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCTCGTATGCCGTCTTCTGCTTG" },
    {"NlaIII-Gex-Adapter1-1", "TCGGACTGTAGAACTCTGAAC", "GTTCAGAGTTCTACAGTCCGA" },
    {"NlaIII-Gex-Adapter1-2", "ACAGGTTCAGAGTTCTACAGTCCGACATG", "CATGTCGGACTGTAGAACTCTGAACCTGT" },
//    {"NlaIII-Gex-Adapter2-1", "CAAGCAGAAGACGGCATACGANN", "NNTCGTATGCCGTCTTCTGCTTG" },
//    {"NlaIII-Gex-Adapter2-2", "TCGTATGCCGTCTTCTGCTTG", "CAAGCAGAAGACGGCATACGA" },
    {"NlaIII-Gex-PCR-Primer1", "CAAGCAGAAGACGGCATACGA", "TCGTATGCCGTCTTCTGCTTG" },
//    {"NlaIII-Gex-PCR-Primer2", "AATGATACGGCGACCACCGACAGGTTCAGAGTTCTACAGTCCGA", "TCGGACTGTAGAACTCTGAACCTGTCGGTGGTCGCCGTATCATT" },
    {"NlaIII-Gex-SequencingPrimer", "CCGACAGGTTCAGAGTTCTACAGTCCGACATG", "CATGTCGGACTGTAGAACTCTGAACCTGTCGG" },
    {"PE-adapters1-1", "GATCGGAAGAGCGGTTCAGCAGGAATGCCGAG", "CTCGGCATTCCTGCTGAACCGCTCTTCCGATC" },
    {"PE-adapters1-2", "ACACTCTTTCCCTACACGACGCTCTTCCGATCT", "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT" },
//    {"PE-sequencingPrimer1", "ACACTCTTTCCCTACACGACGCTCTTCCGATCT", "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT" },
    {"PE-sequencingPrimer2", "CGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT", "AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCG" },
    {"RA5", "GTTCAGAGTTCTACAGTCCGACGATC", "GATCGTCGGACTGTAGAACTCTGAAC" },
    {"RP1", "AATGATACGGCGACCACCGAGATCTACACGTTCAGAGTTCTACAGTCCGA", "TCGGACTGTAGAACTCTGAACGTGTAGATCTCGGTGGTCGCCGTATCATT" },
    {"TruSeq-Adapter-Index-2", "GATCGGAAGAGCACACGTCTGAACTCCAGTCACCGATGTATCTCGTATGCCGTCTTCTGCTTG", "CAAGCAGAAGACGGCATACGAGATACATCGGTGACTGGAGTTCAGACGTGTGCTCTTCCGATC" },
    {"TruSeq-Small-RNA-3'adapter", "TGGAATTCTCGGGTGCCAAGG", "CCTTGGCACCCGAGAATTCCA" },
//    {"TruSeq-Small-RNA-5'adapter", "GTTCAGAGTTCTACAGTCCGACGATC", "GATCGTCGGACTGTAGAACTCTGAAC" },
//    {"TruSeq-Universal-Adapter", "AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT", "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT" },
    {"adaptor1", "CGGAAGAGCGGTTCAGCAGGAATGCCGAGATCGGAAGAGCGG", "CCGCTCTTCCGATCTCGGCATTCCTGCTGAACCGCTCTTCCG" },
    {"adaptor2", "GGTCTGCACCGAAATCTTCTGGACGCTGAGATCGATCCACTCCTTGCCGAGCAA", "TTGCTCGGCAAGGAGTGGATCGATCTCAGCGTCCAGAAGATTTCGGTGCAGACC" },
//    {"adaptor3", "AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT", "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT" },
//    {"adaptor4", "CAAGCAGAAGACGGCATACGAGATCGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT", "AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCTCGTATGCCGTCTTCTGCTTG" },
    {"genomicDNA-adapter1", "GATCGGAAGAGCTCGTATGCCGTCTTCTGCTTG", "CAAGCAGAAGACGGCATACGAGCTCTTCCGATC" },
//    {"genomicDNA-adapter2", "ACACTCTTTCCCTACACGACGCTCTTCCGATCT", "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT" },
//    {"genomicDNA-primer1", "AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT", "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT" },
//    {"genomicDNA-sequencingPrimer", "ACACTCTTTCCCTACACGACGCTCTTCCGATCT", "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT" },
    {"genomicDNA=primer2", "CAAGCAGAAGACGGCATACGAGCTCTTCCGATCT", "AGATCGGAAGAGCTCGTATGCCGTCTTCTGCTTG" },
    {"hybrid-internal-3'adapter", "GACGACATGGCATGTAGGCGGAACCGGCATGTCGTC", "GACGACATGCCGGTTCCGCCTACATGCCATGTCGTC" },
    {"hybrid-internal-5'adapter", "CTGCTGTACCGTACATCCGCCTTGGCCGTACAGCAG", "CTGCTGTACGGCCAAGGCGGATGTACGGTACAGCAG" },
    {"long-insert-2-internal-3'", "CACTAGGCTCCGCACCACGATGTACAACGTCCACAAGCAG", "CTGCTTGTGGACGTTGTACATCGTGGTGCGGAGCCTAGTG" },
    {"long-insert-2-internal-5'", "CTGCTTGTGGACGTTGTACATCGTGGTGCGGAGCCTAGTG", "CACTAGGCTCCGCACCACGATGTACAACGTCCACAAGCAG" },
//    {"smallRNA-3'adapter", "TCGTATGCCGTCTTCTGCTTGT", "ACAAGCAGAAGACGGCATACGA" },
//    {"smallRNA-5'adapter", "GTTCAGAGTTCTACAGTCCGACGATC", "GATCGTCGGACTGTAGAACTCTGAAC" },
    {"smallRNA-PCS-primer1", "CAAGCAGAAGACGGCATACGA", "TCGTATGCCGTCTTCTGCTTG" },
//    {"smallRNA-PCS-primer2", "AATGATACGGCGACCACCGACAGGTTCAGAGTTCTACAGTCCGA", "TCGGACTGTAGAACTCTGAACCTGTCGGTGGTCGCCGTATCATT" },
//    {"smallRNA-RT-primer", "CAAGCAGAAGACGGCATACGA", "TCGTATGCCGTCTTCTGCTTG" },
//    {"smallRNA-sequencingPrimer", "CGACAGGTTCAGAGTTCTACAGTCCGACGATC", "GATCGTCGGACTGTAGAACTCTGAACCTGTCG" },
    { NULL, NULL, NULL }
};

